service:
  name: serverless-with-next

frameworkVersion: ">=1.26.1"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-simulate
  - serverless-jest-plugin
  - serverless-domain-manager

# Enable auto-packing of external modules
# See https://serverless-stack.com/chapters/add-support-for-es6-es7-javascript.html
custom:
  webpackIncludeModules: true
#  webpackIncludeModules:
#    forceInclude:
#      - next
  domains:
    development: 'swn.dev.vadorequest.fr'
  memorySizes: # TODO Check how much is actually needed
    development: 512
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
#    basePath: '' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true
  simulate:
    dist: docker
#    services:
#      file: docker-compose.yml
#      projectName: serverless-with-next

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-east-1'}
  memorySize: ${self:custom.memorySizes.${self:provider.stage}}
  environment:
    NODE_ENV: ${self:provider.stage}


package:
  individually: true

functions:
  server:
    handler: src/functions/server/next.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: /_next/{proxy+}

  status:
    handler: src/functions/status/status.handler
    events:
      - http:
          method: get
          path: status

